version: '3'

services:
  # rocketchatのデータはすべてMongoDBに保存する。
  rocketdb:
    image: mongo:latest
    # 生成時に自動付与されるコンテナ名を明示的に指定する。
    container_name: rocket-db
    # ユーザー定義ネットワークの名前を指定する。
    networks:
      - rocket-tier
    # コンテナが待ち受けるポートを指定する。
    expose:
      - 27017
    # format => voulume-data:container-name:rw
    volumes:
      - rocket-db:/data/db
      - rocket-db-dump:/dump
    command: mongod --smallfiles --oplogSize 128
    restart: always

  rocketchat:
    image: rocketchat/rocket.chat:latest
    container_name: rocket-chat
    restart: always
    networks:
      - rocket-tier
    depends_on:
      - rocketdb
    environment:
      # Change your own URL :)
      - ROOT_URL=https://rocketchat.example.co.jp
      - MONGO_URL=mongodb://rocketdb:27017/rocketchat
    restart: always  

  rocketproxy:
    image: nginx:latest
    container_name: rocket-proxy
    networks:
      - rocket-tier
    ports:
      - 80:80
      - 443:443
    depends_on:
      - rocketchat
      - rocketdb
    # ホスト側で作成したnginx用コンフィグを指定する。
    volumes:
      - /home/rocketchat/rocketproxy/nginx.conf:/etc/nginx/nginx.conf
      - /home/rocketchat/rocketproxy/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - /home/rocketchat/rocketproxy/ssl:/etc/nginx/ssl

# コンテナ停止後も永続化するデータ領域を定義する。      
volumes:
  rocket-db:
    driver: local
  rocket-db-dump:
    driver: local

# ユーザー定義ネットワークを作成する。
networks:
  rocket-tier:
    driver: bridge
