version: '3'

services:
  # WekanのデータはすべてMongoDBに保存する。
  wekandb:
    image: mongo:3.2.19
    # 生成時に自動付与されるコンテナ名を明示的に指定する。
    container_name: wekan-db
    # ユーザー定義ネットワークの名前を指定する。
    networks:
      - wekan-tier
    # コンテナが公開するポートを指定する。
    expose:
      - 27017
    # format => voulume-data:container-name:rw
    volumes:
      - wekan-db:/data/db
      - wekan-db-dump:/dump
    command: mongod --smallfiles --oplogSize 128
    restart: always

  wekan:
    image: quay.io/wekan/wekan
    cotainer_name: wekan-app
    restart: always
    networks:
      - wekan-tier
    depends_on:
      - wekandb
    environment:
      - MONGO_URL=mongodb://wekandb:27017/wekan
      - ROOT_URL=https://<fqdn|host-ip-addr>
      #- MAIL_URL=smtp://user:password@mailserver.example.jp:25/
      #- MAIL_FROM='Example Wekan Support <support@example.jp>'
    restart: always  

  wekanproxy:
    image: nginx:latest
    container_name: wekan-proxy
    networks:
      - wekan-tier
    ports:
      - 80:80
      - 443:443
    depends_on:
      - wekan
      - wekandb
    # ホスト側で作成したnginx用コンフィグを指定する。
    volumes:
      - /var/opt/docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - /var/opt/docker/nginx/cert:/etc/nginx/cert

  # コンテナ停止後も永続化するデータ領域を定義する。      
  # $ dcoker volume ls
  # ---
  # local  wekan-app_wekan-db
  # local  wekan-app_wekna-db-dump
  volumes:
    wekan-db:
      driver: local
    wekan-db-dump:
      driver: local

  # ユーザー定義ネットワークを作成する。
  networks:
    wekan-tier:
      driver: bridge
